### ISSUE TITLE
BOON for PINN

### ISSUE THREAD

**Issue by afrah** [amazon-science/boon#3]
Is this method applicable to the PINN framework?

**Comment by dcmaddix** [comment]
Yes, BOON is applicable to be used with PINNs in the same way that Neural Operators have been with the Physics Informed Neural Operator (PINO) (https://arxiv.org/pdf/2111.03794.pdf) . You can add the differential form of the PDE to the loss function as a regularizer. See the loss function defined in the notebook examples https://github.com/amazon-science/boon/blob/main/notebooks/examples_1d_single_step.ipynb. Note that we benchmark FNO vs. PINO in the paper (https://arxiv.org/abs/2212.07477) and find that PINO does not perform as well. Also in BOON we hard-constrain the neural operator architecture to satisfy the boundary conditions exactly, which we show performs better than incorporating the boundary conditions as soft-constraints in PINO.
